trigger:
  branches:
    include:
      - none
parameters:
  - name: buildConfiguration
    displayName: Select Build Configuration
    type: string
    default: test
    values:
      - test
variables:
  acrLoginServer: crsalarycalculationtest001.azurecr.io
  acrName: crsalarycalculationtest001
  imageName: salarycapturefe-dps
  imageTag: $(Build.BuildId)
  containerAppName: ca-salarycapturefe-test
  resourceGroup: rg-container-test-001
  location: westeurope
  dockerfilePath: 'DockerFile'
  azureSubscription: 'sc-rg-container-test-001'
  dockerContext: '.'
  BUILD_CONFIGURATION: ${{ parameters.buildConfiguration }}

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Image to ACR
  jobs:
  - job: BuildPushImage
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self

    - task: AzureCLI@2
      name: BuildPush
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Logging into ACR..."
          az acr login --name $(acrName)

          echo "Building Docker image with tags: $(imageTag) and latest-dps..."
          docker build -f $(dockerfilePath) \
            -t $(acrLoginServer)/$(imageName):$(imageTag) \
            -t $(acrLoginServer)/$(imageName):latest-dps \
            --build-arg BUILD_CONFIGURATION=${{ parameters.buildConfiguration }} \
            $(dockerContext)

          echo "Pushing Docker image with tag: $(imageTag)..."
          docker push $(acrLoginServer)/$(imageName):$(imageTag)

          echo "Pushing Docker image with tag: latest-dps..."
          docker push $(acrLoginServer)/$(imageName):latest-dps

- stage: DeployToContainerApp
  displayName: Deploy Image to Azure Container App
  dependsOn: BuildAndPush
  jobs:
  - job: Deploy
    displayName: Deploy to ACA
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      name: DeployContainerApp
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Updating ACA image..."
          az containerapp update \
            --name $(containerAppName) \
            --resource-group $(resourceGroup) \
            --image $(acrLoginServer)/$(imageName):latest-dps
          echo "Deployment complete."
