export interface UpdateSalaryLineRequest{
    serviceWorkerId: string,
    productionDate : string,
    organizationUnitId: string,
    jobNumber ?: string,
    tenantId ?: string,
    vehicleTypeId ?: string,
    description ?: string,
    startTime : string,
    endTime : string,
    totalTime ?: string,
    kilometers ?: number,
    expectedHours ?: number,
    expectedMinutes ?: number,
    trackedHours ?: number,
    trackedMinutes ?: number,
    salaryAmount : number,
    lineTypeId: string,
    statusId : number,
    salaryId ?: string,
    line: string,
    payer: string,
    startLocation ?: string,
    endLocation ?: string,
    KMTime ?: string,
    id : string
}